from enum import StrEnum


class FailureCode(StrEnum):
    VIDEO_UNAVAILABLE = "VIDEO_UNAVAILABLE"
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
    PIPELINE_FAILED = "PIPELINE_FAILED"
